# Generated by Django 3.0.4 on 2020-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20200326_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='DEFAULT_VALUE', max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='creator',
            field=models.CharField(default='DEFAULT_VALUE', max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='paradigm',
            field=models.CharField(default='DEFAULT_VALUE', max_length=20),
        ),
        migrations.AddField(
            model_name='programmer',
            name='age',
            field=models.IntegerField(default='18'),
        ),
    ]
